module.exports = {
  tableName: "users",
  columnNames: {
    id: "uuid",
    email: "email",
    password: "password",
    firstname: "firstname",
    middlename: "middlename",
    lastname: "lastname",
    suffix: "suffix",
    maidenname: "maidenname",
    accessLevel: "access_level",
    position: "position",
    dateHired: "date_hired",
    birthday: "birthday",
    civilStatus: "civil_status",
    contactNumber: "contact_number",
    address: "address",
    sss: "sss",
    tin: "tin",
    hdmf: "hdmf",
    philhealth: "philhealth",
    emergencyContactPerson: "emergency_contact_person",
    emergencyContactNumber: "emergency_contact_number",
    qrCode: "qr_code",
    fingerprint: "fingerprint",
    status: "status",
    refreshToken: "refresh_token",
  },
};
